@startuml BudgetAdd
'https://plantuml.com/sequence-diagram

actor User
participant Parser
participant BudgetParser
participant Budget

User -> Parser: "budget"
activate Parser
Parser -> BudgetParser: start()
deactivate Parser
activate BudgetParser
BudgetParser -> Budget: resetWeeklyBudget(boolean carryOver)
activate Budget
Budget -> Budget: saveBudgetData()
deactivate Budget
BudgetParser -> Budget: resetIfNeeded()
activate Budget
Budget -> Budget: saveBudgetData()
deactivate Budget
BudgetParser -->> User: "Enter command (add X, deduct X, view, exit)"
deactivate BudgetParser

User -> BudgetParser: "add 100"
activate BudgetParser
BudgetParser -> Budget: addWeeklyBudget(100)
deactivate BudgetParser
activate Budget
Budget -> Budget: saveBudgetData()
Budget -->> User: "Added $100.00 to this week's budget. Remaining weekly budget: $100"
deactivate Budget

User -> BudgetParser: "view"
activate BudgetParser
BudgetParser -> Budget: viewExpenses()
deactivate BudgetParser
activate Budget
Budget -->> User: "Remaining weekly budget: $100\nTotal spent today: $0\nTotal spent this week: $15\nTotal spent this month: $40"
deactivate Budget

@enduml