@startuml
actor User
participant "CanteenLookupStartup" as CLS
participant "CanteenLookup" as CL
participant "CanteenDataProcessor" as CDP

User -> CLS : startCanteenLookup()

loop until command == "exit"
    User -> CLS : enter command
    alt Invalid Shortcut
        CLS -> CLS : notify invalid canteen
    else Valid Shortcut
        CLS -> CL : lookupCanteen(canteenName)
        CL -> CDP : processData()
        deactivate CDP
        alt Canteen not found
            CL -> CL : throw CanteenNotFound
        else
            CL -> CLS : show canteen stalls
        end
        deactivate CL
    end
end

CLS -> CLS : show exit message
deactivate CLS
@enduml
