@startuml

actor Navi
participant Storage
participant CanteenDataProcessor
participant FacultyDataProcessor
participant HostelDataProcessor
participant OtherBuildingDataProcessor
participant Faculty
participant Landmark
participant Canteen
participant Stall

activate Navi
    Navi -> Storage : processDataFromFiles()
    activate Storage
        Storage -> CanteenDataProcessor : processData()
        activate CanteenDataProcessor
            CanteenDataProcessor -> CanteenDataProcessor : insertCanteenFromData(canteenData)
            activate CanteenDataProcessor
            CanteenDataProcessor -> Canteen : new Canteen(canteenName)
            activate Canteen
                Canteen -> Stall : addStall(stallData)
                activate Stall
                Stall -->> Canteen : return
                deactivate Stall
            Canteen -->> CanteenDataProcessor : return
            deactivate Canteen
            CanteenDataProcessor -->> Storage : return (canteenMap populated)
            deactivate CanteenDataProcessor
        deactivate CanteenDataProcessor

        Storage -> FacultyDataProcessor : processData(faculties)
        activate FacultyDataProcessor
            FacultyDataProcessor -> FacultyDataProcessor : insertFacultyFromData(facultyData, faculties)
            activate FacultyDataProcessor
            FacultyDataProcessor -> Faculty : new Faculty(facultyName)
            activate Faculty
                Faculty -> Canteen : setNearestCanteens(canteen)
                activate Canteen
                Canteen -->> Faculty : return
                deactivate Canteen

                Faculty -> Canteen : setCanteenDistance(canteen, distance)
                activate Canteen
                Canteen -->> Faculty : return
                deactivate Canteen
            Faculty -->> FacultyDataProcessor : return
            deactivate Faculty
            FacultyDataProcessor -->> Storage : return (faculties populated)
            deactivate FacultyDataProcessor
        deactivate FacultyDataProcessor

        Storage -> HostelDataProcessor : processData(hostels)
        activate HostelDataProcessor
            HostelDataProcessor -> HostelDataProcessor : insertHostelFromData(hostelData, hostels)
            activate HostelDataProcessor
            HostelDataProcessor -> Landmark : new Landmark(hostelName)
            activate Landmark
                Landmark -> Canteen : setNearestCanteens(canteen)
                activate Canteen
                Canteen -->> Landmark : return
                deactivate Canteen

                Landmark -> Canteen : setCanteenDistance(canteen, distance)
                activate Canteen
                Canteen -->> Landmark : return
                deactivate Canteen
            Landmark -->> HostelDataProcessor : return
            deactivate Landmark
            HostelDataProcessor -->> Storage : return (hostels populated)
            deactivate HostelDataProcessor
        deactivate HostelDataProcessor

        Storage -> OtherBuildingDataProcessor : processData(otherBuildings)
        activate OtherBuildingDataProcessor
            OtherBuildingDataProcessor -> OtherBuildingDataProcessor : insertOtherBuildingFromData(otherBuildingData, otherBuildings)
            activate OtherBuildingDataProcessor
            OtherBuildingDataProcessor -> Landmark : new Landmark(otherBuildingName)
            activate Landmark
                Landmark -> Canteen : setNearestCanteens(canteen)
                activate Canteen
                Canteen -->> Landmark : return
                deactivate Canteen

                Landmark -> Canteen : setCanteenDistance(canteen, distance)
                activate Canteen
                Canteen -->> Landmark : return
                deactivate Canteen
            Landmark -->> OtherBuildingDataProcessor : return
            deactivate Landmark
            OtherBuildingDataProcessor -->> Storage : return (otherBuildings populated)
            deactivate OtherBuildingDataProcessor
        deactivate OtherBuildingDataProcessor
    Storage -->> Navi : return (LANDMARKS populated)
    deactivate Storage
deactivate Navi

@enduml
