@startuml
' Hide the bottom lifeline boxes (those vertical dashed lines with the "X" at the bottom)
hide footbox

Actor Navi

participant Storage
participant CanteenDataProcessor
participant FacultyDataProcessor
participant HostelDataProcessor
participant OtherBuildingDataProcessor
participant DataRetriever
participant CanteenFinderParser

Navi -> Storage : processDataFromFiles()
activate Storage

Storage -> Storage : clear canteenMap

Storage -> CanteenDataProcessor : new CanteenDataProcessor(canteenMap)
activate CanteenDataProcessor
deactivate CanteenDataProcessor

Storage -> CanteenDataProcessor : processData()
activate CanteenDataProcessor
CanteenDataProcessor -> DataRetriever : getCanteenData()
activate DataRetriever
DataRetriever --> CanteenDataProcessor : List<String> canteenData
deactivate DataRetriever
CanteenDataProcessor -->> Storage : update canteenMap with Canteens and Stalls
deactivate CanteenDataProcessor

Storage -> FacultyDataProcessor : new FacultyDataProcessor(canteenMap)
activate FacultyDataProcessor
deactivate FacultyDataProcessor

Storage -> FacultyDataProcessor : processData(faculties)
activate FacultyDataProcessor
FacultyDataProcessor -> DataRetriever : getFacultyData()
activate DataRetriever
DataRetriever --> FacultyDataProcessor : List<String> facultyData
deactivate DataRetriever
FacultyDataProcessor -->> Storage : update faculties list with Faculty objects
deactivate FacultyDataProcessor

Storage -> HostelDataProcessor : new HostelDataProcessor(canteenMap)
activate HostelDataProcessor
deactivate HostelDataProcessor

Storage -> HostelDataProcessor : processData(hostels)
activate HostelDataProcessor
HostelDataProcessor -> DataRetriever : getHostelData()
activate DataRetriever
DataRetriever --> HostelDataProcessor : List<String> hostelData
deactivate DataRetriever
HostelDataProcessor -->> Storage : update hostels list with Landmark objects
deactivate HostelDataProcessor

Storage -> OtherBuildingDataProcessor : new OtherBuildingDataProcessor(canteenMap)
activate OtherBuildingDataProcessor
deactivate OtherBuildingDataProcessor

Storage -> OtherBuildingDataProcessor : processData(otherBuildings)
activate OtherBuildingDataProcessor
OtherBuildingDataProcessor -> DataRetriever : getOtherBuildingData()
activate DataRetriever
DataRetriever --> OtherBuildingDataProcessor : List<String> buildingData
deactivate DataRetriever
OtherBuildingDataProcessor -->> Storage : update otherBuildings list with Landmark objects
deactivate OtherBuildingDataProcessor

Storage -> CanteenFinderParser : LANDMARKS.addAll(faculties, hostels, otherBuildings)
deactivate Storage
@enduml
