@startuml
' Hide the footbox (X marks at the end of lifelines)
hide footbox

actor Navi

participant Storage
participant CanteenDataProcessor
participant FacultyDataProcessor
participant HostelDataProcessor
participant OtherBuildingDataProcessor
participant DataRetriever
participant CanteenFinderParser

Navi -> Storage : processDataFromFiles()
activate Storage

Storage -> Storage : clear CANTEEN_MAP

' --- Canteen Data Processing ---


Storage -> CanteenDataProcessor : new CanteenDataProcessor(canteenMap)
activate CanteenDataProcessor
CanteenDataProcessor -> DataRetriever : getCanteenData()
activate DataRetriever
DataRetriever --> CanteenDataProcessor : List<String> canteenData
deactivate DataRetriever
deactivate CanteenDataProcessor


' --- Faculty Data Processing ---
Storage -> FacultyDataProcessor : new FacultyDataProcessor(canteenMap)
activate FacultyDataProcessor
FacultyDataProcessor -> DataRetriever : getFacultyData()
activate DataRetriever
DataRetriever --> FacultyDataProcessor : List<String> facultyData
deactivate DataRetriever
deactivate FacultyDataProcessor

Storage -> FacultyDataProcessor : processData()
activate FacultyDataProcessor
FacultyDataProcessor --> Storage : add Faculty objects to LANDMARKS
deactivate FacultyDataProcessor

' --- Hostel Data Processing ---
Storage -> HostelDataProcessor : new HostelDataProcessor(canteenMap)
activate HostelDataProcessor
HostelDataProcessor -> DataRetriever : getHostelData()
activate DataRetriever
DataRetriever --> HostelDataProcessor : List<String> hostelData
deactivate DataRetriever
deactivate HostelDataProcessor

Storage -> HostelDataProcessor : processData()
activate HostelDataProcessor
HostelDataProcessor --> Storage : add Hostel Landmarks to LANDMARKS
deactivate HostelDataProcessor

' --- Other Building Data Processing ---
Storage -> OtherBuildingDataProcessor : new OtherBuildingDataProcessor(canteenMap)
activate OtherBuildingDataProcessor
OtherBuildingDataProcessor -> DataRetriever : getOtherBuildingData()
activate DataRetriever
DataRetriever --> OtherBuildingDataProcessor : List<String> buildingData
deactivate DataRetriever
deactivate OtherBuildingDataProcessor

Storage -> OtherBuildingDataProcessor : processData()
activate OtherBuildingDataProcessor
OtherBuildingDataProcessor --> Storage : add Other Landmarks to LANDMARKS
deactivate OtherBuildingDataProcessor


' --- Final Aggregation ---
Storage -> CanteenFinderParser : LANDMARKS.addAll(faculties, hostels, otherBuildings)
deactivate Storage
@enduml
