@startuml

actor Navi
participant Storage
participant CanteenDataProcessor
participant FacultyDataProcessor
participant HostelDataProcessor
participant OtherBuildingDataProcessor
participant Faculty
participant Landmark
participant Canteen
participant Stall

Navi -> Storage : processDataFromFiles()
Storage -> CanteenDataProcessor : processData()
CanteenDataProcessor -> CanteenDataProcessor : insertCanteenFromData(canteenData)
CanteenDataProcessor -> Canteen : new Canteen(canteenName)
Canteen -> Stall : addStall(stallData)
Storage -> FacultyDataProcessor : processData(faculties)
FacultyDataProcessor -> FacultyDataProcessor : insertFacultyFromData(facultyData, faculties)
FacultyDataProcessor -> Faculty : new Faculty(facultyName)
Faculty -> Canteen : setNearestCanteens(canteen)
Faculty -> Canteen : setCanteenDistance(canteen, distance)
Storage -> HostelDataProcessor : processData(hostels)
HostelDataProcessor -> HostelDataProcessor : insertHostelFromData(hostelData, hostels)
HostelDataProcessor -> Landmark : new Landmark(hostelName)
Landmark -> Canteen : setNearestCanteens(canteen)
Landmark -> Canteen : setCanteenDistance(canteen, distance)
Storage -> OtherBuildingDataProcessor : processData(otherBuildings)
OtherBuildingDataProcessor -> OtherBuildingDataProcessor : insertOtherBuildingFromData(otherBuildingData, otherBuildings)
OtherBuildingDataProcessor -> Landmark : new Landmark(otherBuildingName)
Landmark -> Canteen : setNearestCanteens(canteen)
Landmark -> Canteen : setCanteenDistance(canteen, distance)

@enduml